version: '2'
services:
  chartmuseum:
    build:
      context: .
    environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /charts
    ports:
      - '8080:8080'
    volumes:
      - chartmuseum_data:/charts
volumes:
  chartmuseum_data:
    driver: local