---
AWSTemplateFormatVersion: '2010-09-09'

Description: >

    Chart Museum for Fargate on AWS

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Setup"
        Parameters: 
          - VPCID
          - PublicSubnet1ID
          - PublicSubnet2ID
          - CredentialsParameter
          - InstanceCount
          - CertificateArn

Parameters:

    VPCID: 
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the Application should be deployed to
        AllowedPattern: .+
        ConstraintDescription: Please choose VPC

    PublicSubnet1ID:
        Type: "AWS::EC2::Subnet::Id"
        Description: The ID of the public subnet in Availability Zone 1 in your existing VPC (e.g., subnet-a0246dcd)

    PublicSubnet2ID:
        Type: "AWS::EC2::Subnet::Id"
        Description: The ID of the public subnet in Availability Zone 2 in your existing VPC (e.g., subnet-b1236eea)

    InstanceCount:
        Description: 'Number of instances behind load balancer.  Minimum 2 required for high availability.'
        Default: 2
        AllowedValues: [1, 2, 3, 4, 5]
        Type: Number

    CredentialsParameter:
        Type: String
        Description: DockerHub Secret
        Default: ''

    CertificateArn:
        Type: String
        Description: CertificateArn for SSL cert that matches the FQDN above. Please visit the AWS Certificate Manager.

Resources:

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/solodev-cms/cloudformation/infrastructure/alb.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !Ref VPCID
                CertificateArn: !Ref CertificateArn
                Subnets: !Join [",", [!Ref PublicSubnet1ID, !Ref PublicSubnet2ID]]

    FARGATE:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/solodev-cms/cloudformation/infrastructure/fargate.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !Ref VPCID
                LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
                Subnets: !Join [",", [!Ref PublicSubnet1ID, !Ref PublicSubnet2ID]]

    CHARTS:
        Type: AWS::CloudFormation::Stack
        DependsOn: FARGATE
        Properties:
            TemplateURL: https://s3.amazonaws.com/charts-museum/cloudformation/service.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !Ref VPCID
                Cluster: !GetAtt FARGATE.Outputs.Cluster
                ClusterArn: !GetAtt FARGATE.Outputs.ClusterArn
                LoadBalancer: !GetAtt ALB.Outputs.LoadBalancer
                LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
                Subnets: !Join [",", [!Ref PublicSubnet1ID, !Ref PublicSubnet2ID]]
                CredentialsParameter: !Ref CredentialsParameter
                CertificateArn: !Ref CertificateArn
                DesiredCount: !Ref InstanceCount
                ServiceRole: !GetAtt ALB.Outputs.ServiceRole 
                Path: / 

Outputs:
    AppUrl: 
        Description: The URL endpoint for the load balancer. Point your DNS to this CNAME.
        Value: !GetAtt ALB.Outputs.LoadBalancerUrl